apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 256071863627.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 256071863627.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 422db02f
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
